apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  # image tags are relative; to specify an image repo (e.g. GCR), you
  # must provide a "default repo" using one of the methods described 
  # here:
  # https://skaffold.dev/docs/concepts/#image-repository-handling
  - image: todoservice
    context: src/todoservice
  - image: userservice
    context: src/userservice
  tagPolicy:
    gitCommit: {}
deploy:
  kubectl:
    manifests:
    - ./kubernetes-manifests/**.yaml
profiles:
# "travis-ci" profile is used to build the images without
# pushing them.
- name: travis-ci
  build:
    local:
      push: false
# "gcb" profile allows building and pushing the images
# on Google Container Builder without requiring docker
# installed on the developer machine. However, note that
# since GCB does not cache the builds, each build will
# start from scratch and therefore take a long time.
#
# This is not used by default. To use it, run:
#     skaffold run -p gcb
- name: gcb
  build:
    googleCloudBuild:
      diskSizeGb: 300
      machineType: N1_HIGHCPU_32
      timeout: 4000s
