// Code generated by protoc-gen-go. DO NOT EDIT.
// source: todohq.proto

package todohq

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Task we have to do
type Todo struct {
	// Unique integer identifier of the todo task
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Title of the task
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// Detail description of the todo task
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Date and time to remind the todo task
	Reminder             *timestamp.Timestamp `protobuf:"bytes,4,opt,name=reminder,proto3" json:"reminder,omitempty"`
	OwnerId              string               `protobuf:"bytes,5,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Todo) Reset()         { *m = Todo{} }
func (m *Todo) String() string { return proto.CompactTextString(m) }
func (*Todo) ProtoMessage()    {}
func (*Todo) Descriptor() ([]byte, []int) {
	return fileDescriptor_36f800d961521875, []int{0}
}

func (m *Todo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Todo.Unmarshal(m, b)
}
func (m *Todo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Todo.Marshal(b, m, deterministic)
}
func (m *Todo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Todo.Merge(m, src)
}
func (m *Todo) XXX_Size() int {
	return xxx_messageInfo_Todo.Size(m)
}
func (m *Todo) XXX_DiscardUnknown() {
	xxx_messageInfo_Todo.DiscardUnknown(m)
}

var xxx_messageInfo_Todo proto.InternalMessageInfo

func (m *Todo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Todo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Todo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Todo) GetReminder() *timestamp.Timestamp {
	if m != nil {
		return m.Reminder
	}
	return nil
}

func (m *Todo) GetOwnerId() string {
	if m != nil {
		return m.OwnerId
	}
	return ""
}

type ListTodosResponse struct {
	Todos                []*Todo  `protobuf:"bytes,1,rep,name=todos,proto3" json:"todos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTodosResponse) Reset()         { *m = ListTodosResponse{} }
func (m *ListTodosResponse) String() string { return proto.CompactTextString(m) }
func (*ListTodosResponse) ProtoMessage()    {}
func (*ListTodosResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_36f800d961521875, []int{1}
}

func (m *ListTodosResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTodosResponse.Unmarshal(m, b)
}
func (m *ListTodosResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTodosResponse.Marshal(b, m, deterministic)
}
func (m *ListTodosResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTodosResponse.Merge(m, src)
}
func (m *ListTodosResponse) XXX_Size() int {
	return xxx_messageInfo_ListTodosResponse.Size(m)
}
func (m *ListTodosResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTodosResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListTodosResponse proto.InternalMessageInfo

func (m *ListTodosResponse) GetTodos() []*Todo {
	if m != nil {
		return m.Todos
	}
	return nil
}

type GetTodoRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTodoRequest) Reset()         { *m = GetTodoRequest{} }
func (m *GetTodoRequest) String() string { return proto.CompactTextString(m) }
func (*GetTodoRequest) ProtoMessage()    {}
func (*GetTodoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_36f800d961521875, []int{2}
}

func (m *GetTodoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTodoRequest.Unmarshal(m, b)
}
func (m *GetTodoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTodoRequest.Marshal(b, m, deterministic)
}
func (m *GetTodoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTodoRequest.Merge(m, src)
}
func (m *GetTodoRequest) XXX_Size() int {
	return xxx_messageInfo_GetTodoRequest.Size(m)
}
func (m *GetTodoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTodoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTodoRequest proto.InternalMessageInfo

func (m *GetTodoRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type FilterTodosRequest struct {
	OwnerId              string   `protobuf:"bytes,1,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FilterTodosRequest) Reset()         { *m = FilterTodosRequest{} }
func (m *FilterTodosRequest) String() string { return proto.CompactTextString(m) }
func (*FilterTodosRequest) ProtoMessage()    {}
func (*FilterTodosRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_36f800d961521875, []int{3}
}

func (m *FilterTodosRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterTodosRequest.Unmarshal(m, b)
}
func (m *FilterTodosRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterTodosRequest.Marshal(b, m, deterministic)
}
func (m *FilterTodosRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterTodosRequest.Merge(m, src)
}
func (m *FilterTodosRequest) XXX_Size() int {
	return xxx_messageInfo_FilterTodosRequest.Size(m)
}
func (m *FilterTodosRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterTodosRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FilterTodosRequest proto.InternalMessageInfo

func (m *FilterTodosRequest) GetOwnerId() string {
	if m != nil {
		return m.OwnerId
	}
	return ""
}

type FilterTodosResponse struct {
	Results              []*Todo  `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FilterTodosResponse) Reset()         { *m = FilterTodosResponse{} }
func (m *FilterTodosResponse) String() string { return proto.CompactTextString(m) }
func (*FilterTodosResponse) ProtoMessage()    {}
func (*FilterTodosResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_36f800d961521875, []int{4}
}

func (m *FilterTodosResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterTodosResponse.Unmarshal(m, b)
}
func (m *FilterTodosResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterTodosResponse.Marshal(b, m, deterministic)
}
func (m *FilterTodosResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterTodosResponse.Merge(m, src)
}
func (m *FilterTodosResponse) XXX_Size() int {
	return xxx_messageInfo_FilterTodosResponse.Size(m)
}
func (m *FilterTodosResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterTodosResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FilterTodosResponse proto.InternalMessageInfo

func (m *FilterTodosResponse) GetResults() []*Todo {
	if m != nil {
		return m.Results
	}
	return nil
}

type CreateRequest struct {
	// Task entity to add
	Todo                 *Todo    `protobuf:"bytes,1,opt,name=todo,proto3" json:"todo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_36f800d961521875, []int{5}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetTodo() *Todo {
	if m != nil {
		return m.Todo
	}
	return nil
}

// Contains data of created todo task
type CreateResponse struct {
	// ID of created task
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_36f800d961521875, []int{6}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UpdateRequest struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	HasTitle             bool                 `protobuf:"varint,2,opt,name=hasTitle,proto3" json:"hasTitle,omitempty"`
	TitleValue           string               `protobuf:"bytes,3,opt,name=titleValue,proto3" json:"titleValue,omitempty"`
	HasDescription       bool                 `protobuf:"varint,4,opt,name=hasDescription,proto3" json:"hasDescription,omitempty"`
	DescriptionValue     string               `protobuf:"bytes,5,opt,name=descriptionValue,proto3" json:"descriptionValue,omitempty"`
	HasReminder          bool                 `protobuf:"varint,6,opt,name=hasReminder,proto3" json:"hasReminder,omitempty"`
	ReminderValue        *timestamp.Timestamp `protobuf:"bytes,7,opt,name=reminderValue,proto3" json:"reminderValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_36f800d961521875, []int{7}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateRequest) GetHasTitle() bool {
	if m != nil {
		return m.HasTitle
	}
	return false
}

func (m *UpdateRequest) GetTitleValue() string {
	if m != nil {
		return m.TitleValue
	}
	return ""
}

func (m *UpdateRequest) GetHasDescription() bool {
	if m != nil {
		return m.HasDescription
	}
	return false
}

func (m *UpdateRequest) GetDescriptionValue() string {
	if m != nil {
		return m.DescriptionValue
	}
	return ""
}

func (m *UpdateRequest) GetHasReminder() bool {
	if m != nil {
		return m.HasReminder
	}
	return false
}

func (m *UpdateRequest) GetReminderValue() *timestamp.Timestamp {
	if m != nil {
		return m.ReminderValue
	}
	return nil
}

type UpdateResponse struct {
	Todo                 *Todo    `protobuf:"bytes,2,opt,name=todo,proto3" json:"todo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_36f800d961521875, []int{8}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetTodo() *Todo {
	if m != nil {
		return m.Todo
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_36f800d961521875, []int{9}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_36f800d961521875, []int{10}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_36f800d961521875, []int{11}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type Token struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Valid                bool     `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_36f800d961521875, []int{12}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Token) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func init() {
	proto.RegisterType((*Todo)(nil), "todohq.Todo")
	proto.RegisterType((*ListTodosResponse)(nil), "todohq.ListTodosResponse")
	proto.RegisterType((*GetTodoRequest)(nil), "todohq.GetTodoRequest")
	proto.RegisterType((*FilterTodosRequest)(nil), "todohq.FilterTodosRequest")
	proto.RegisterType((*FilterTodosResponse)(nil), "todohq.FilterTodosResponse")
	proto.RegisterType((*CreateRequest)(nil), "todohq.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "todohq.CreateResponse")
	proto.RegisterType((*UpdateRequest)(nil), "todohq.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "todohq.UpdateResponse")
	proto.RegisterType((*Empty)(nil), "todohq.Empty")
	proto.RegisterType((*User)(nil), "todohq.User")
	proto.RegisterType((*UserResponse)(nil), "todohq.UserResponse")
	proto.RegisterType((*Token)(nil), "todohq.Token")
}

func init() { proto.RegisterFile("todohq.proto", fileDescriptor_36f800d961521875) }

var fileDescriptor_36f800d961521875 = []byte{
	// 639 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x8e, 0x53, 0x27, 0x69, 0x27, 0x4d, 0x04, 0x4b, 0xa9, 0x8c, 0x91, 0x20, 0x5a, 0x89, 0xaa,
	0x02, 0xc9, 0xa1, 0xa9, 0x44, 0xc5, 0x01, 0x09, 0xc4, 0x4f, 0x41, 0xe2, 0x64, 0xd2, 0x9e, 0xb8,
	0xb8, 0xf5, 0xd0, 0x58, 0x75, 0xbc, 0xee, 0xee, 0xba, 0x15, 0xcf, 0xc1, 0x0b, 0xf0, 0x1a, 0x5c,
	0x79, 0x32, 0xb4, 0xbb, 0x5e, 0xc7, 0x76, 0x8a, 0xe0, 0xb6, 0x33, 0xf3, 0xcd, 0xec, 0xcc, 0x37,
	0xf3, 0xc1, 0xb6, 0x64, 0x31, 0x5b, 0x5c, 0x05, 0x39, 0x67, 0x92, 0x91, 0xbe, 0xb1, 0xfc, 0xc7,
	0x17, 0x8c, 0x5d, 0xa4, 0x38, 0xd5, 0xde, 0xb3, 0xe2, 0xdb, 0x54, 0x26, 0x4b, 0x14, 0x32, 0x5a,
	0xe6, 0x06, 0x48, 0x7f, 0x3a, 0xe0, 0xce, 0x59, 0xcc, 0xc8, 0x18, 0xba, 0x49, 0xec, 0x39, 0x13,
	0x67, 0x7f, 0x2b, 0xec, 0x26, 0x31, 0xd9, 0x81, 0x9e, 0x4c, 0x64, 0x8a, 0x5e, 0x57, 0xbb, 0x8c,
	0x41, 0x26, 0x30, 0x8c, 0x51, 0x9c, 0xf3, 0x24, 0x97, 0x09, 0xcb, 0xbc, 0x0d, 0x1d, 0xab, 0xbb,
	0xc8, 0x0b, 0xd8, 0xe4, 0xb8, 0x4c, 0xb2, 0x18, 0xb9, 0xe7, 0x4e, 0x9c, 0xfd, 0xe1, 0xcc, 0x0f,
	0x4c, 0x13, 0x81, 0x6d, 0x22, 0x98, 0xdb, 0x26, 0xc2, 0x0a, 0x4b, 0x3c, 0x18, 0xb0, 0x9b, 0x0c,
	0xf9, 0xa7, 0xd8, 0xeb, 0xe9, 0xaa, 0xd6, 0xa4, 0x47, 0x70, 0xf7, 0x73, 0x22, 0xa4, 0xea, 0x52,
	0x84, 0x28, 0x72, 0x96, 0x09, 0x24, 0x14, 0x7a, 0x6a, 0x44, 0xe1, 0x39, 0x93, 0x8d, 0xfd, 0xe1,
	0x6c, 0x3b, 0x28, 0xc7, 0x57, 0xa8, 0xd0, 0x84, 0xe8, 0x04, 0xc6, 0xc7, 0xa8, 0xf3, 0x42, 0xbc,
	0x2a, 0x50, 0xc8, 0xf6, 0x90, 0x34, 0x00, 0xf2, 0x21, 0x49, 0x25, 0xf2, 0xb2, 0xb8, 0x41, 0xd5,
	0x5a, 0x71, 0x9a, 0xad, 0xbc, 0x82, 0x7b, 0x0d, 0x7c, 0xd9, 0xcc, 0x1e, 0x0c, 0x38, 0x8a, 0x22,
	0x95, 0xb7, 0xb7, 0x63, 0x83, 0xf4, 0x00, 0x46, 0x6f, 0x39, 0x46, 0x12, 0xed, 0x4f, 0x13, 0x70,
	0x15, 0x50, 0x7f, 0xd3, 0xce, 0xd2, 0x11, 0x35, 0x83, 0x4d, 0x29, 0x3f, 0x6b, 0xcf, 0xf0, 0xa3,
	0x0b, 0xa3, 0x93, 0x3c, 0xae, 0x55, 0x6d, 0xaf, 0xd2, 0x87, 0xcd, 0x45, 0x24, 0xe6, 0xd5, 0x36,
	0x37, 0xc3, 0xca, 0x26, 0x8f, 0x00, 0xf4, 0x66, 0x4f, 0xa3, 0xb4, 0xc0, 0x72, 0x9f, 0x35, 0x0f,
	0xd9, 0x83, 0xf1, 0x22, 0x12, 0xef, 0x6a, 0x3b, 0x77, 0x75, 0x85, 0x96, 0x97, 0x3c, 0x85, 0x3b,
	0xb5, 0x2b, 0x30, 0xd5, 0xcc, 0x1e, 0xd7, 0xfc, 0xea, 0x88, 0x16, 0x91, 0x08, 0xed, 0x95, 0xf4,
	0x75, 0xc1, 0xba, 0x8b, 0xbc, 0x86, 0x91, 0x3d, 0x0c, 0x53, 0x6a, 0xf0, 0xcf, 0x4b, 0x6a, 0x26,
	0xd0, 0x19, 0x8c, 0x2d, 0x29, 0x25, 0x6f, 0x96, 0xeb, 0xee, 0x5f, 0xb9, 0x1e, 0x40, 0xef, 0xfd,
	0x32, 0x97, 0xdf, 0xe9, 0x57, 0x70, 0x4f, 0x04, 0xf2, 0x35, 0x22, 0x09, 0xb8, 0x59, 0xb4, 0xb4,
	0x92, 0xd0, 0x6f, 0xa5, 0x13, 0x5c, 0x46, 0x49, 0x5a, 0x72, 0x67, 0x0c, 0x45, 0x79, 0x1e, 0x09,
	0x71, 0xc3, 0x78, 0xac, 0x09, 0xdb, 0x0a, 0x2b, 0x9b, 0x3e, 0x87, 0x6d, 0x55, 0xbd, 0xde, 0x58,
	0x21, 0x90, 0xb7, 0x8f, 0x40, 0x63, 0x74, 0x84, 0x1e, 0x42, 0x6f, 0xce, 0x2e, 0x31, 0xd3, 0xa2,
	0x54, 0x8f, 0xb2, 0x27, 0x63, 0x28, 0xef, 0x75, 0x94, 0x26, 0x71, 0xb9, 0x5c, 0x63, 0xcc, 0x7e,
	0x75, 0x61, 0xa8, 0x86, 0xfb, 0x82, 0xfc, 0x3a, 0x39, 0x47, 0x72, 0x04, 0x5b, 0x95, 0x8c, 0xc8,
	0xc8, 0xfe, 0xa2, 0x07, 0xf6, 0x1f, 0x58, 0x73, 0x4d, 0x68, 0xb4, 0x43, 0x0e, 0x60, 0x50, 0xca,
	0x88, 0xec, 0x5a, 0x5c, 0x53, 0x57, 0x7e, 0x83, 0x4d, 0xda, 0x21, 0x1f, 0x61, 0x58, 0xd3, 0x09,
	0xf1, 0x6d, 0x78, 0x5d, 0x6c, 0xfe, 0xc3, 0x5b, 0x63, 0xd5, 0xe7, 0x2f, 0xa1, 0x6f, 0xee, 0x9f,
	0xdc, 0xb7, 0xc0, 0x86, 0x84, 0xfc, 0xdd, 0xb6, 0xbb, 0x9e, 0x6a, 0x4e, 0x60, 0x95, 0xda, 0xd0,
	0xc9, 0x2a, 0xb5, 0x79, 0x29, 0xb4, 0x33, 0xfb, 0xed, 0xc0, 0x50, 0xf1, 0x6f, 0xb9, 0x0b, 0xaa,
	0x2e, 0x1a, 0xeb, 0xf1, 0x77, 0x1a, 0xcb, 0x5a, 0x7d, 0xfd, 0x0c, 0x36, 0x8e, 0x51, 0xfe, 0x27,
	0xf8, 0x09, 0xb8, 0x6f, 0x0a, 0xb9, 0x68, 0xa1, 0x47, 0x2b, 0x4a, 0x2f, 0x31, 0xa3, 0x1d, 0x32,
	0x85, 0xd1, 0xa9, 0x5a, 0x6c, 0x24, 0xd1, 0x1c, 0x43, 0x13, 0xb1, 0x96, 0x70, 0xd6, 0xd7, 0x2a,
	0x39, 0xfc, 0x13, 0x00, 0x00, 0xff, 0xff, 0x80, 0x53, 0xf7, 0x05, 0x1a, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TodoServiceClient is the client API for TodoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TodoServiceClient interface {
	ListTodos(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListTodosResponse, error)
	GetTodo(ctx context.Context, in *GetTodoRequest, opts ...grpc.CallOption) (*Todo, error)
	FilterTodos(ctx context.Context, in *FilterTodosRequest, opts ...grpc.CallOption) (*FilterTodosResponse, error)
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
}

type todoServiceClient struct {
	cc *grpc.ClientConn
}

func NewTodoServiceClient(cc *grpc.ClientConn) TodoServiceClient {
	return &todoServiceClient{cc}
}

func (c *todoServiceClient) ListTodos(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListTodosResponse, error) {
	out := new(ListTodosResponse)
	err := c.cc.Invoke(ctx, "/todohq.TodoService/ListTodos", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) GetTodo(ctx context.Context, in *GetTodoRequest, opts ...grpc.CallOption) (*Todo, error) {
	out := new(Todo)
	err := c.cc.Invoke(ctx, "/todohq.TodoService/GetTodo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) FilterTodos(ctx context.Context, in *FilterTodosRequest, opts ...grpc.CallOption) (*FilterTodosResponse, error) {
	out := new(FilterTodosResponse)
	err := c.cc.Invoke(ctx, "/todohq.TodoService/FilterTodos", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/todohq.TodoService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/todohq.TodoService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TodoServiceServer is the server API for TodoService service.
type TodoServiceServer interface {
	ListTodos(context.Context, *Empty) (*ListTodosResponse, error)
	GetTodo(context.Context, *GetTodoRequest) (*Todo, error)
	FilterTodos(context.Context, *FilterTodosRequest) (*FilterTodosResponse, error)
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
}

// UnimplementedTodoServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTodoServiceServer struct {
}

func (*UnimplementedTodoServiceServer) ListTodos(ctx context.Context, req *Empty) (*ListTodosResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTodos not implemented")
}
func (*UnimplementedTodoServiceServer) GetTodo(ctx context.Context, req *GetTodoRequest) (*Todo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTodo not implemented")
}
func (*UnimplementedTodoServiceServer) FilterTodos(ctx context.Context, req *FilterTodosRequest) (*FilterTodosResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FilterTodos not implemented")
}
func (*UnimplementedTodoServiceServer) Create(ctx context.Context, req *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedTodoServiceServer) Update(ctx context.Context, req *UpdateRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}

func RegisterTodoServiceServer(s *grpc.Server, srv TodoServiceServer) {
	s.RegisterService(&_TodoService_serviceDesc, srv)
}

func _TodoService_ListTodos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).ListTodos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todohq.TodoService/ListTodos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).ListTodos(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_GetTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTodoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).GetTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todohq.TodoService/GetTodo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).GetTodo(ctx, req.(*GetTodoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_FilterTodos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilterTodosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).FilterTodos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todohq.TodoService/FilterTodos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).FilterTodos(ctx, req.(*FilterTodosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todohq.TodoService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todohq.TodoService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServiceServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TodoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "todohq.TodoService",
	HandlerType: (*TodoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListTodos",
			Handler:    _TodoService_ListTodos_Handler,
		},
		{
			MethodName: "GetTodo",
			Handler:    _TodoService_GetTodo_Handler,
		},
		{
			MethodName: "FilterTodos",
			Handler:    _TodoService_FilterTodos_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _TodoService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _TodoService_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "todohq.proto",
}

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	Create(ctx context.Context, in *User, opts ...grpc.CallOption) (*UserResponse, error)
	Get(ctx context.Context, in *User, opts ...grpc.CallOption) (*UserResponse, error)
	Auth(ctx context.Context, in *User, opts ...grpc.CallOption) (*Token, error)
	ValidateToken(ctx context.Context, in *Token, opts ...grpc.CallOption) (*Token, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) Create(ctx context.Context, in *User, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/todohq.UserService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Get(ctx context.Context, in *User, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/todohq.UserService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Auth(ctx context.Context, in *User, opts ...grpc.CallOption) (*Token, error) {
	out := new(Token)
	err := c.cc.Invoke(ctx, "/todohq.UserService/Auth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ValidateToken(ctx context.Context, in *Token, opts ...grpc.CallOption) (*Token, error) {
	out := new(Token)
	err := c.cc.Invoke(ctx, "/todohq.UserService/ValidateToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	Create(context.Context, *User) (*UserResponse, error)
	Get(context.Context, *User) (*UserResponse, error)
	Auth(context.Context, *User) (*Token, error)
	ValidateToken(context.Context, *Token) (*Token, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) Create(ctx context.Context, req *User) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedUserServiceServer) Get(ctx context.Context, req *User) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedUserServiceServer) Auth(ctx context.Context, req *User) (*Token, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Auth not implemented")
}
func (*UnimplementedUserServiceServer) ValidateToken(ctx context.Context, req *Token) (*Token, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateToken not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todohq.UserService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Create(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todohq.UserService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Get(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todohq.UserService/Auth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Auth(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ValidateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Token)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ValidateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/todohq.UserService/ValidateToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ValidateToken(ctx, req.(*Token))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "todohq.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _UserService_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _UserService_Get_Handler,
		},
		{
			MethodName: "Auth",
			Handler:    _UserService_Auth_Handler,
		},
		{
			MethodName: "ValidateToken",
			Handler:    _UserService_ValidateToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "todohq.proto",
}
